version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: on-failure
    networks:
      - main

  alembic:
    build:
      context: .
    command: sh -c "alembic upgrade head"
    volumes:
      - .:/app
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - main

  fastapi:
    build:
      context: .
    command: sh -c "uvicorn app.backend.main:app --reload --host='0.0.0.0'"
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - .:/app
    depends_on:
      - postgres
      - alembic
    restart: always
    networks:
      - main

  frontend:
    build:
      context: .
      dockerfile: dockerfile_frontend
    command: sh -c "live-server --host=0.0.0.0 app/frontend"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - fastapi
    restart: on-failure
    networks:
      - main

networks:
  main:
    driver: bridge
    name: main
    ipam:
      driver: default
      config:
        - subnet: 172.26.13.0/24





